title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  - ps -ef|grep 'facegit'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - echo "zzz end"
link: https://github.com/midoks/zzz
